#version: '3.9'
#
#services:
#  web:
#    build: .
#    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/code
#      - static_volume:/code/static
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db
#    env_file:
#      - .env
#
#  db:
#    image: postgres:16.0
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    environment:
#      POSTGRES_DB: ${NAME}
#      POSTGRES_USER: ${USER}
#      POSTGRES_PASSWORD: ${PASSWORD}
#    env_file:
#      - ./.env
#
#volumes:
#  postgres_data:
#  static_volume:

version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - static_volume:/code/static
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health/" ]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:16.0
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${NAME}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER} -d ${NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 5s
      retries: 3

  celery:
    build: .
    command: celery -A config worker --loglevel=info
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - .:/code

  celery-beat:
    build: .
    command: celery -A config beat --loglevel=info
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - .:/code

volumes:
  postgres_data:
  static_volume:
  redis_data: