# Generated by Django 5.2.3 on 2025-06-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_alter_lesson_video_link_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(default=0, verbose_name="Цена курса"),
        ),
    ]
